import { Library } from "@site/data/dataTypes";
type raw_items_types = { libraries: Library[]; total: number };
export const raw_items: raw_items_types = {
  libraries: [
    {
      githubUrl: "https://github.com/react-native-maps/react-native-maps",
      ios: true,
      android: true,
      expoGo: true,
      examples: ["https://snack.expo.dev/H1zOFxnN-"],
      goldstar: true,
      github: {
        urls: {
          repo: "https://github.com/react-native-maps/react-native-maps",
          clone: "https://github.com/react-native-maps/react-native-maps.git",
          homepage: null,
        },
        stats: {
          hasIssues: true,
          hasWiki: false,
          hasPages: false,
          hasDownloads: true,
          hasTopics: true,
          updatedAt: "2024-05-24T10:07:32Z",
          createdAt: "2015-12-29T19:54:20Z",
          pushedAt: "2024-05-24T10:07:32Z",
          forks: 4588,
          issues: 40,
          subscribers: 215,
          stars: 14811,
        },
        name: "react-native-maps",
        fullName: "react-native-maps/react-native-maps",
        description: "React Native Mapview component for iOS + Android",
        topics: [
          "react",
          "react-native",
          "react-component",
          "map",
          "mapview",
          "google-maps",
          "mapkit",
          "maps",
        ],
        license: {
          key: "mit",
          name: "MIT License",
          spdxId: "MIT",
          url: "http://choosealicense.com/licenses/mit/",
          id: "MDc6TGljZW5zZTEz",
        },
        lastRelease: {
          name: "v1.15.3",
          tagName: "v1.15.3",
          createdAt: "2024-05-24T10:07:32Z",
          publishedAt: "2024-05-24T10:07:40Z",
          isPrerelease: false,
        },
        hasTypes: false,
        newArchitecture: false,
      },
      images: [],
      npmPkg: "react-native-maps",
      npm: {
        downloads: 1060284,
        start: "2024-04-24",
        end: "2024-05-23",
        period: "month",
        weekDownloads: 231311,
      },
      score: 100,
      matchingScoreModifiers: [
        "Very popular",
        "Popular",
        "Recommended",
        "Recently updated",
      ],
      popularity: -0.032,
      topicSearchString:
        "react react-native react-component map mapview google-maps mapkit maps",
    },
    {
      githubUrl: "https://github.com/FormidableLabs/react-native-app-auth",
      examples: [
        "https://github.com/FormidableLabs/react-native-app-auth/tree/master/Example",
        "https://github.com/FormidableLabs/react-native-app-auth/tree/master/Example#react-native-app-auth-example",
      ],
      ios: true,
      android: true,
      github: {
        urls: {
          repo: "https://github.com/FormidableLabs/react-native-app-auth",
          clone: "https://github.com/FormidableLabs/react-native-app-auth.git",
          homepage: "",
        },
        stats: {
          hasIssues: true,
          hasWiki: false,
          hasPages: false,
          hasDownloads: true,
          hasTopics: true,
          updatedAt: "2024-05-24T09:55:02Z",
          createdAt: "2017-11-13T17:59:31Z",
          pushedAt: "2024-05-24T09:55:02Z",
          forks: 402,
          issues: 93,
          subscribers: 58,
          stars: 1935,
        },
        name: "react-native-app-auth",
        fullName: "FormidableLabs/react-native-app-auth",
        description:
          "React native bridge for AppAuth - an SDK for communicating with OAuth2 providers",
        topics: [
          "react",
          "react-native",
          "auth",
          "authentication",
          "oauth",
          "oauth2",
          "appauth",
        ],
        license: {
          key: "mit",
          name: "MIT License",
          spdxId: "MIT",
          url: "http://choosealicense.com/licenses/mit/",
          id: "MDc6TGljZW5zZTEz",
        },
        lastRelease: {
          name: "v7.2.0",
          tagName: "v7.2.0",
          createdAt: "2024-05-14T14:34:12Z",
          publishedAt: "2024-05-14T14:34:13Z",
          isPrerelease: false,
        },
        hasTypes: true,
        newArchitecture: false,
      },
      images: [],
      npmPkg: "react-native-app-auth",
      npm: {
        downloads: 265078,
        start: "2024-04-24",
        end: "2024-05-23",
        period: "month",
        weekDownloads: 55211,
      },
      score: 50,
      matchingScoreModifiers: [
        "Popular",
        "Lots of open issues",
        "Recently updated",
      ],
      popularity: -0.042,
      topicSearchString:
        "react react-native auth authentication oauth oauth2 appauth",
    },
  ],
  total: 1398,
};
