name: documentation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  checks:
    name: Run Build Check
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        # with:
        #   node-version: '18'
        #   cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Install dependencies
        run: pnpm install --recursive --frozen-lockfile --strict-peer-dependencies

      - name: Build website
        run: cd website/similar-react-native-libraries && pnpm build

  deploy:
    name: Deploy to GitHub Pages
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        # with:
        #   node-version: '18'
        #   cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Install dependencies
        run: pnpm install --recursive --strict-peer-dependencies

      - name: Build website
        run: cd website/similar-react-native-libraries && pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN_SIMILAR_REACT_NATIVE_LIB }}
          publish_dir: website/similar-react-native-libraries/build
          user_name: mrpmohiburrahman
          user_email: 35300157+mrpmohiburrahman@users.noreply.github.com
